
import "./globals.css";
import Nav from "../Components/Nav.jsx"



export const metadata = {
  title: "Next-Todo-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        
        <Nav/>

        {children}
        </body>
    </html>
  );
}
